session:
  cache:
    ttl-seconds: 120

authentication:
  service-id: authentication-service

server:
  port: 8081
  forward-headers-strategy: framework
  netty:
    # Timeout plus long pour WebSocket et Socket.io
    idle-timeout: PT120S

security:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001,https://hideously-smart-llama.ngrok-free.app,http://localhost:19006
    mobile-patterns: exp://*,exps://*,capacitor://localhost,ionic://localhost,http://127.0.0.1:*,http://10.0.2.2:*,http://192.168.*:*
  jwt:
    secret: 9a4f2c_8d3b7a1e6f#45c8a0b3f268b1d4e6-f3c8a9d2b5f8e3a9c8-b5f6v8a3d9A@
    cookie:
      access-token: "accessToken"

spring:
  application:
    name: api-gateway
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+01:00
  jackson:
    time-zone: GMT+01:00
  cloud:
    gateway:
      # Configuration globale
      globalcors:
        # Désactivé car géré par CorsGlobalConfiguration
        enabled: false
      forwarded:
        enabled: true

      # Désactiver la découverte automatique des routes
      discovery:
        locator:
          enabled: false

      # Routes - ORDRE CRITIQUE: Socket.io AVANT WebSocket AVANT HTTP
      routes:
        # =============================================================================
        # ROUTE 1: Socket.io Transport (WebSocket + Polling combiné)
        # Path direct /socket.io/**
        # =============================================================================
        - id: order-service-socketio-direct
          uri: http://localhost:9092
          predicates:
            - Path=/socket.io/**
          filters:
            - PreserveHostHeader

        # =============================================================================
        # ROUTE 2: Socket.io avec préfixe API (WebSocket)
        # Path /api/order/socket.io/** pour WebSocket
        # =============================================================================
        - id: order-service-socketio-api-ws
          uri: http://localhost:9092
          predicates:
            - Path=/api/order/socket.io/**
            - Header=Upgrade, websocket
          filters:
            - PreserveHostHeader
            - RewritePath=/api/order/socket.io/(?<segment>.*), /socket.io/${segment}

        # =============================================================================
        # ROUTE 3: Socket.io avec préfixe API (Polling)
        # Path /api/order/socket.io/** pour HTTP polling
        # =============================================================================
        - id: order-service-socketio-api-polling
          uri: http://localhost:9092
          predicates:
            - Path=/api/order/socket.io/**
          filters:
            - PreserveHostHeader
            - RewritePath=/api/order/socket.io/(?<segment>.*), /socket.io/${segment}

        # =============================================================================
        # ROUTE 4: WebSocket STOMP natif (legacy)
        # =============================================================================
        - id: order-service-websocket-native
          uri: lb:ws://order-service
          predicates:
            - Path=/api/order/ws/websocket
          filters:
            - PreserveHostHeader

        # =============================================================================
        # ROUTE 5: SockJS (legacy)
        # =============================================================================
        - id: order-service-sockjs
          uri: lb:ws://order-service
          predicates:
            - Path=/api/order/ws/**
          filters:
            - PreserveHostHeader

        # =============================================================================
        # ROUTE 6: Endpoints de test Socket.io
        # =============================================================================
        - id: order-service-socketio-test
          uri: lb://order-service
          predicates:
            - Path=/api/order/socketio/**
          filters:
            - PreserveHostHeader

        # =============================================================================
        # ROUTE 7: HTTP Standard pour Order Service
        # =============================================================================
        - id: order-service-http
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - PreserveHostHeader

        # =============================================================================
        # ROUTE 8: Inventory Service
        # =============================================================================
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**

        # =============================================================================
        # ROUTE 9: User Service
        # =============================================================================
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        # =============================================================================
        # ROUTE 10: Authentication Service
        # =============================================================================
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**

      # Configuration HTTP Client pour Socket.io - CRITIQUE
      httpclient:
        # Configuration WebSocket
        websocket:
          # Taille max des frames (Socket.io peut envoyer de gros messages)
          max-frame-payload-length: 65536  # 64KB
          # Pas de proxy ping pour Socket.io (il gère ses propres pings)
          proxy-ping: false
        # Pool de connexions
        pool:
          type: elastic
          max-idle-time: 120s
          max-connections: 1000
          acquire-timeout: 45000
        # Timeouts
        connect-timeout: 10000
        response-timeout: 120s
        # Compression désactivée pour Socket.io
        compression: false
        # Wiretap pour debug (activer si besoin)
        wiretap: false

      # Configuration des métriques
      metrics:
        enabled: true
        tags:
          path:
            enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    metadata-map:
      websocket-enabled: true
      socketio-enabled: true
      socketio-port: 9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,routes
  endpoint:
    gateway:
      enabled: true
    routes:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.filter.factory: INFO
    org.springframework.web.reactive.socket: INFO
    reactor.netty: INFO
    reactor.netty.http.client: INFO
    io.netty.handler.codec.http.websocketx: INFO
    com.bacos.mokengeli.biloko: DEBUG

# Timeouts Reactor Netty pour Socket.io
reactor:
  netty:
    pool:
      max-idle-time: 120000  # 2 minutes
      max-life-time: 600000  # 10 minutes
    http:
      server:
        compression: false

# Paths publics (incluant Socket.io)
gateway:
  public-paths: /public/**, /api/auth/login, /api/order/ws/test, /api/order/socketio/**, /socket.io/**