session:
  cache:
    ttl-seconds: 120
authentication:
  service-id: authentication-service
server:
  port: 8080
security:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001,https://hideously-smart-llama.ngrok-free.app
    mobile-patterns: exp://*,exps://*,capacitor://localhost,ionic://localhost,http://127.0.0.1:*,http://10.0.2.2:*,http://192.168.*:*
  jwt:
    secret: 9a4f2c_8d3b7a1e6f#45c8a0b3f268b1d4e6-f3c8a9d2b5f8e3a9c8-b5f6v8a3d9A@
    cookie:
      access-token: "accessToken"
spring:
  application:
    name: api-gateway
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+01:00
  jackson:
    time-zone: GMT+01:00
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    #org.springframework.web.cors: DEBUG
    #reactor.netty.http.server: DEBUG

gateway:
  public-paths:  public/**, /api/auth/login, /api/order/ws/**