session:
  cache:
    ttl-seconds: ${SESSION_CACHE_TTL:120}

authentication:
  service-id: authentication-service

server:
  port: ${SERVER_PORT}
  forward-headers-strategy: framework
  netty:
    # Timeout plus long pour WebSocket
    idle-timeout: ${WEBSOCKET_IDLE_TIMEOUT:PT120S}

security:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
    mobile-patterns: ${MOBILE_PATTERNS}
  jwt:
    secret: ${JWT_SECRET}
    cookie:
      access-token: "accessToken"

spring:
  application:
    name: api-gateway
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: ${TIME_ZONE:GMT+01:00}
  jackson:
    time-zone: ${TIME_ZONE:GMT+01:00}
  cloud:
    gateway:
      # Configuration globale
      globalcors:
        # Désactivé car géré par CorsGlobalConfiguration
        enabled: false
      forwarded:
        enabled: true
      # Routes - ORDRE IMPORTANT: WebSocket AVANT les routes standard
      routes:
        # Route WebSocket pour Order Service - DOIT ÊTRE EN PREMIER
        - id: order-service-websocket
          uri: lb:ws://order-service
          predicates:
            - Path=/api/order/ws/**
          filters:
            # Préserver le path et les headers pour WebSocket
            - PreserveHostHeader

        # Route standard pour Order Service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**

        # Route pour Inventory Service
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**

        # Route pour User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        # Route pour Authentication Service
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**

      # Configuration HTTP Client pour WebSocket
      httpclient:
        # Configuration WebSocket
        websocket:
          # Taille max des frames WebSocket (640KB)
          max-frame-payload-length: ${WEBSOCKET_MAX_FRAME_SIZE:655360}
          # Proxy automatique des sous-protocoles
          proxy-ping: true
        # Pool de connexions
        pool:
          # Type de pool elastic pour WebSocket
          type: elastic
          # Temps d'inactivité avant fermeture
          max-idle-time: 30s
          # Nombre max de connexions
          max-connections: 500
        # Timeouts de connexion
        connect-timeout: ${WEBSOCKET_CONNECT_TIMEOUT:30000}
        # Timeout de réponse (120 secondes pour WebSocket)
        response-timeout: ${WEBSOCKET_RESPONSE_TIMEOUT:120s}
        # Compression (activée pour les requêtes HTTP standard)
        compression: true

      # Configuration des métriques
      metrics:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
    # Rafraîchissement plus fréquent pour WebSocket
    registry-fetch-interval-seconds: 5
  instance:
    # Heartbeat plus fréquent
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    gateway:
      access: unrestricted

logging:
  level:
    # Logging principal
    org.springframework.cloud.gateway: ${LOG_LEVEL:INFO}
    org.springframework.web.cors: ${LOG_LEVEL:INFO}
    # Logging spécifique WebSocket (activé en DEBUG pour diagnostic)
    org.springframework.web.reactive.socket: ${WEBSOCKET_LOG_LEVEL:DEBUG}
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: ${ROUTE_LOG_LEVEL:DEBUG}
    # Logging Netty pour debug WebSocket
    reactor.netty.http.server: ${NETTY_LOG_LEVEL:DEBUG}
    reactor.netty.http.client: ${NETTY_LOG_LEVEL:DEBUG}
    io.netty.handler.codec.http.websocketx: ${NETTY_LOG_LEVEL:DEBUG}
    # Logging des filtres
    com.bacos.mokengeli.biloko.filter: ${FILTER_LOG_LEVEL:DEBUG}

# Timeouts Reactor Netty pour WebSocket
reactor:
  netty:
    pool:
      # Temps d'inactivité max
      max-idle-time: 60000
      # Durée de vie max d'une connexion
      max-life-time: 300000
    http:
      server:
        # Désactiver la compression pour WebSocket
        compression: false

gateway:
  public-paths: ${PUBLIC_PATHS:public/**,/api/auth/login}