session:
  cache:
    ttl-seconds: 120

authentication:
  service-id: authentication-service

server:
  port: 8081
  forward-headers-strategy: framework
  netty:
    idle-timeout: PT30S

security:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001,https://hideously-smart-llama.ngrok-free.app,http://localhost:8080,http://192.168.1.151:8080
    mobile-patterns: exp://*,exps://*,capacitor://localhost,ionic://localhost,http://127.0.0.1:*,http://10.0.2.2:*,http://192.168.*:*,http://localhost:8080
  jwt:
    secret: 9a4f2c_8d3b7a1e6f#45c8a0b3f268b1d4e6-f3c8a9d2b5f8e3a9c8-b5f6v8a3d9A@
    cookie:
      access-token: "accessToken"

spring:
  application:
    name: api-gateway
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+01:00
  jackson:
    time-zone: GMT+01:00
  cloud:
    gateway:
      # Configuration globale
      globalcors:
        # Désactivé car géré par CorsGlobalConfiguration
        enabled: false
      forwarded:
        enabled: true

      # Désactiver la découverte automatique des routes
      discovery:
        locator:
          enabled: false

      # Routes
      routes:
        # =============================================================================
        # Order Service
        # =============================================================================
        - id: order-service-http
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - PreserveHostHeader

        # =============================================================================
        # Inventory Service
        # =============================================================================
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**

        # =============================================================================
        # User Service
        # =============================================================================
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        # =============================================================================
        # Authentication Service
        # =============================================================================
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**

      # Configuration HTTP Client
      httpclient:
        pool:
          type: elastic
          max-idle-time: 30s
          max-connections: 500
          acquire-timeout: 30000
        connect-timeout: 10000
        response-timeout: 60s

      # Configuration des métriques
      metrics:
        enabled: true
        tags:
          path:
            enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    metadata-map:
      gateway-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,routes
  endpoint:
    gateway:
      access: unrestricted
    routes:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.filter.factory: INFO
    org.springframework.web.reactive.socket: INFO
    reactor.netty: INFO
    reactor.netty.http.client: INFO
    io.netty.handler.codec.http.websocketx: INFO
    com.bacos.mokengeli.biloko: DEBUG

# Timeouts Reactor Netty
reactor:
  netty:
    pool:
      max-idle-time: 60000
      max-life-time: 300000
    http:
      server:
        compression: true

# Paths publics
gateway:
  public-paths: /public/**, /api/auth/login